name: features
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Network
  #dio: ^4.0.6

  #Database
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0

  #State Management
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0

  #Fonts
  #google_fonts: ^3.0.1

  #image picker
  image_picker: ^0.8.6

  gallery_saver: ^2.3.2

  #Date time formatting
  #intl: ^0.17.0

  # Animations
  #flutter_spinkit: ^5.1.0
  lottie: ^1.4.3

  #currency text format
  #flutter_masked_text2: ^0.9.1

  #Permission Handler
  permission_handler: ^10.2.0

  #Barcode Scanner
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.0.0

  #Packege and version information
  package_info_plus: ^3.0.1

  # Helper
  group_radio_button: ^1.2.0

  # Camera
  camera: ^0.10.0+3



  #Find the correct path
  path_provider: ^2.0.11
  path: ^1.8.2
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

