name: flutter_features
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Network
  dio: ^5.3.2

  #State Management
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5

  # Hooks
  # flutter_hooks: ^0.20.0
  
  #Flash Bar
  # another_flushbar: ^1.12.29
  # smooth_page_indicator: ^1.0.0+2

  #Fonts
  #google_fonts: ^3.0.1

  #image picker
  # image_picker: ^1.0.1
  # image_downloader: ^0.31.0
  # gallery_saver: ^2.3.2

  #Date time formatting
  #intl: ^0.17.0

  # Animations
  #flutter_spinkit: ^5.1.0

  #Loading Animation
  lottie: ^2.0.0

  #currency text format
  #flutter_masked_text2: ^0.9.1

  #Permission Handler
  permission_handler: ^10.2.0

  #Barcode Scanner
  # flutter_barcode_scanner: ^2.0.0
  # qr_flutter: ^4.0.0
  # qr_code_scanner: ^1.0.1

  #Packege and version information
  package_info_plus: ^4.1.0

  #Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Helper
  # group_radio_button: ^1.2.0

  # Camera
  # camera: ^0.10.0+3

  #app to app
  # app_launcher: ^1.0.0

  #Find the correct path
  path_provider: ^2.0.11
  path: ^1.8.2
  
  #Full Screen
  # fullscreen: ^1.0.3
  
  # SVG Files 
  flutter_svg: ^2.0.7

  # Airplane Mode
  airplane_mode_checker: ^2.0.0

  cupertino_icons: ^1.0.2 
  kartal: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/yuvarlak_opak.svg
    - assets/png/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

